[package]
name = "local-first-notes"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
bytes = "1"
iroh = { workspace = true, default-features = false }
iroh-app.workspace = true
iroh-blobs = { workspace = true, default-features = false }
iroh-docs.workspace = true
tokio = { version = "1", features = ["io-util", "macros", "rt-multi-thread", "time"] }
