#!/usr/bin/env bash
# Applies the Krikos rebrand mechanical sweep (ADR-0002 / .superpowers plan
# Task 3), driven entirely by scripts/rename-map.toml.
#
# STATUS: historical, one-shot tool. It performed the Task 3 sweep once
# (commit ba8314b819), already applied and committed to this repository --
# `--dry-run` against the current tree reports zero remaining changes, and
# it is expected to keep reporting zero indefinitely. It is kept rather than
# deleted (Task 7 decision) for two reasons: it is a reviewable, executable
# record of exactly how the sweep was performed, rather than a paragraph
# describing it after the fact; and its `--dry-run` mode remains a genuinely
# useful audit tool for the standing cost ADR-0002 accepted -- every future
# upstream protocol sync (docs/framework/upstream-sync.md) reimports files
# that can reintroduce old, pre-rebrand-named Rust identifiers into an
# already-renamed directory, and re-running `--dry-run` after an import
# lists exactly which files need the rename reapplied by hand.
#
# Do NOT run `--apply` again as a whole-repo operation: every directory in
# its move plan already has its new name, so `--apply` hits its own
# `FATAL: expected source directory '...' does not exist` guard on the
# first pair and exits before touching anything -- a safe, loud failure,
# not a silent no-op or a corruption, but not a usable "reapply the sweep"
# path either. Fix any straggler `--dry-run` flags by hand, using the exact
# old->new pairs in scripts/rename-map.toml, then confirm with
# scripts/tests/check-rebrand-complete.sh.
#
# Kept working, not just kept: two bugs that would have made `--dry-run`
# lie were found and fixed on 2026-07-30, after Task 5 (a later commit)
# added `pattern`-keyed exemptions to rename-map.toml that this script
# predates -- `is_exempt` raised `KeyError: 'path'` on any `pattern`-only
# exemption instead of skipping it, and the inline-array branch
# (`members = [...]` / `exclude = [...]`) counted a "change" whenever it
# matched a quoted string at all, not when the substitution actually
# changed anything, so any inline array with a quoted entry (e.g.
# `members = ["."]` in fuzz/Cargo.toml) was misreported as needing a
# rewrite it didn't need. Both are fixed in place below; neither changes
# what counts as a real rename.
#
# Usage:
#   scripts/apply-rebrand.sh --dry-run   # report what would change, write nothing
#   scripts/apply-rebrand.sh --apply     # git mv directories + rewrite content
#
# What this touches (and ONLY this -- see rationale in the plan/report):
#   1. The 12 directories in rename-map.toml with dir_renamed = true, via
#      `git mv` (so history follows).
#   2. Every `Cargo.toml`: `name =`, `[lib] name =`, `path =` dependency
#      values, bare dependency-table keys, workspace `members`/`exclude`
#      arrays, `[workspace.dependencies]`, feature-forwarding strings
#      ("krikos-blobs/rpc", "dep:krikos") -- everything else (repository URLs,
#      descriptions, license, comments, third-party deps like iroh-metrics/
#      iroh-io/iroh-test) is deliberately left alone.
#   3. Every `.rs` file: identifiers matching an `old_lib`/`old_package`
#      token exactly, bounded so `iroh-metrics`, `krikos_docsrs` and similar
#      unrelated or intentionally-out-of-scope identifiers are never
#      corrupted.
#   4. A narrow, separately-reported exception: the `path =`/`package =`
#      fields (only) in the three compat/*/Cargo.toml files' *-v2/-current
#      dependency entries, which alias THIS repo's own renamed packages by
#      local path -- see the script-level comment near COMPAT_FIX below.
#
# `Cargo.lock` is deliberately NOT rewritten here; it is regenerated by
# `cargo check`/`cargo generate-lockfile` after this script runs, and that
# regeneration is verified separately to touch nothing but the renames.
#
# ORDERING: every substitution list below is independently sorted longest-
# key-first and asserted free of prefix violations before anything is
# written, mirroring (and re-deriving, not trusting) the invariant
# check-rebrand-complete.sh enforces on the map itself.
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

mode="${1:-}"
if [[ "$mode" != "--dry-run" && "$mode" != "--apply" ]]; then
  echo "usage: $0 --dry-run|--apply" >&2
  exit 2
fi

# --- Step A: directory renames (git mv) -------------------------------------
# Done in bash, driven by a python-computed, order-safe, nesting-safe plan.
mv_plan=$(python3 - "$repo_root" <<'PY'
import sys, tomllib
from pathlib import Path

root = Path(sys.argv[1])
m = tomllib.load(open(root / "scripts" / "rename-map.toml", "rb"))
pairs = [(p["old_dir"], p["new_dir"]) for p in m["packages"] if p["old_dir"] != p["new_dir"]]
# Independently re-derive the safe order for DIRECTORY paths: sort longest
# old_dir first. This does NOT necessarily match old_package's order --
# e.g. old_dir "protocols/krikos-gossip" (21 chars) is longer than old_dir
# "krikos-runtime" (12 chars) even though old_package "krikos-gossip" is
# shorter than old_package "krikos-runtime" -- so it must be computed fresh,
# not inherited from the packages list's own order.
pairs.sort(key=lambda t: -len(t[0]))
for i, (a, _) in enumerate(pairs):
    for b, _ in pairs[i + 1:]:
        if a != b and b.startswith(a):
            print(f"ORDER-VIOLATION: {a!r} is a prefix of later entry {b!r}", file=sys.stderr)
            sys.exit(1)
# A directory move is skipped (handled automatically by its ancestor's move)
# if its old_dir is nested under another move's old_dir.
old_dirs = {a for a, _ in pairs}
skip = set()
for old, _ in pairs:
    for other in old_dirs:
        if other != old and old.startswith(other + "/"):
            skip.add(old)
for old, new in pairs:
    if old in skip:
        print(f"SKIP\t{old}\t{new}\t(nested under an ancestor move)")
    else:
        print(f"MOVE\t{old}\t{new}")
PY
)

echo "=== Directory rename plan ==="
echo "$mv_plan"
echo

while IFS=$'\t' read -r action old new _rest; do
  [[ -z "$action" ]] && continue
  if [[ "$action" == "SKIP" ]]; then
    continue
  fi
  if [[ "$mode" == "--apply" ]]; then
    if [[ ! -e "$old" ]]; then
      echo "FATAL: expected source directory '$old' does not exist" >&2
      exit 1
    fi
    if [[ -e "$new" ]]; then
      echo "FATAL: destination '$new' already exists" >&2
      exit 1
    fi
    git mv "$old" "$new"
    echo "moved: $old -> $new"
  fi
done <<< "$mv_plan"

if [[ "$mode" == "--apply" ]]; then
  # Sanity-check the nested case explicitly: krikos/bench must now exist as
  # a consequence of the krikos -> krikos move, with no separate mv needed.
  if [[ ! -d krikos/bench ]]; then
    echo "FATAL: krikos/bench does not exist after the krikos -> krikos move" >&2
    exit 1
  fi
fi
echo

# --- Step B: content rewrite (manifests + Rust sources) ---------------------
python3 - "$repo_root" "$mode" <<'PYEOF'
import re
import subprocess
import sys
import tomllib
from pathlib import Path

root = Path(sys.argv[1])
mode = sys.argv[2]
dry_run = mode == "--dry-run"

map_path = root / "scripts" / "rename-map.toml"
rename_map = tomllib.load(open(map_path, "rb"))
packages = rename_map["packages"]
exemptions = rename_map.get("exemptions", [])

# ---------------------------------------------------------------------------
# Ordering: re-derive and assert, never trust file order blindly.
# ---------------------------------------------------------------------------
def assert_no_prefix_violations(pairs, label):
    for i, (a, _) in enumerate(pairs):
        for b, _ in pairs[i + 1:]:
            if a != b and b.startswith(a):
                sys.exit(
                    f"FATAL: {label} ordering violation: {a!r} (earlier) is a "
                    f"strict prefix of {b!r} (later). Refusing to run."
                )

# old_package: assert the file order itself is already longest-first (this
# is what check-rebrand-complete.sh also enforces on the map), then use it.
pkg_pairs_file_order = [
    (p["old_package"], p["new_package"]) for p in packages if p["old_package"] != p["new_package"]
]
assert_no_prefix_violations(pkg_pairs_file_order, "old_package (file order)")
# Belt-and-suspenders: independently re-sort and confirm it's the SAME
# order, so a future edit that silently reorders the file (but keeps it
# technically prefix-safe under some other order) cannot slip through.
pkg_pairs_resorted = sorted(pkg_pairs_file_order, key=lambda t: -len(t[0]))
if pkg_pairs_resorted != pkg_pairs_file_order:
    sys.exit(
        "FATAL: [[packages]] file order is not identical to a strict "
        "descending-length sort of old_package. Refusing to run -- fix the "
        "map or make this script re-sort explicitly."
    )
pkg_pairs = pkg_pairs_file_order
pkg_map = dict(pkg_pairs)

# old_lib: independently sorted, NOT assumed to inherit old_package's order.
lib_pairs = sorted(
    ((p["old_lib"], p["new_lib"]) for p in packages if p["old_lib"] != p["new_lib"]),
    key=lambda t: -len(t[0]),
)
assert_no_prefix_violations(lib_pairs, "old_lib")
lib_map = dict(lib_pairs)

# old_dir: independently sorted (see the bash step above for why this
# cannot be inherited from old_package's order either -- protocols/*
# directories are longer than sibling top-level old_package names).
dir_pairs = sorted(
    ((p["old_dir"], p["new_dir"]) for p in packages if p["old_dir"] != p["new_dir"]),
    key=lambda t: -len(t[0]),
)
assert_no_prefix_violations(dir_pairs, "old_dir")

print(f"Loaded {len(pkg_pairs)} package renames, {len(lib_pairs)} lib renames, "
      f"{len(dir_pairs)} directory renames from {map_path.relative_to(root)}.")

# ---------------------------------------------------------------------------
# Exemption glob matching -- ported verbatim from
# scripts/tests/check-rebrand-complete.sh so the two stay in lockstep.
# ---------------------------------------------------------------------------
import fnmatch as _fnmatch


def _glob_match(path_parts, pattern_parts):
    if not pattern_parts:
        return not path_parts
    head, rest = pattern_parts[0], pattern_parts[1:]
    if head == "**":
        if _glob_match(path_parts, rest):
            return True
        if path_parts and _glob_match(path_parts[1:], pattern_parts):
            return True
        return False
    if not path_parts:
        return False
    if not _fnmatch.fnmatchcase(path_parts[0], head):
        return False
    return _glob_match(path_parts[1:], rest)


def glob_match(path, pattern):
    return _glob_match(path.split("/"), pattern.split("/"))


def is_exempt(path):
    # NOTE: `exemptions` can also contain `pattern`-keyed entries (added by
    # Task 5 to scripts/rename-map.toml, after this script was written) that
    # exempt one literal substring wherever it occurs rather than a whole
    # path. This script only ever needs whole-file exemption for its
    # directory/manifest/`.rs`-content sweep, so `pattern`-only entries are
    # simply skipped here rather than applied -- but they MUST be skipped
    # explicitly (`"path" in e`), not assumed absent, or an `e["path"]`
    # lookup on a `pattern`-only entry raises `KeyError`.
    return any(glob_match(path, e["path"]) for e in exemptions if "path" in e)


# ---------------------------------------------------------------------------
# Bounded-token substitution helpers.
#
# Hyphen is included in the "word" class for package/dir matching: without
# this, a bounded search for old_package "krikos" WOULD match inside the
# unrelated third-party dependency "iroh-metrics" (boundary chars on a
# naive [A-Za-z0-9_] class are "-" on both sides, which look like valid
# boundaries but aren't -- "iroh-metrics" is a different word, not "krikos"
# followed by more of "iroh-metrics"). Requiring the char immediately
# outside the match to be outside [A-Za-z0-9_-] rejects that while still
# matching the old_package/old_dir string's OWN internal hyphens, which are
# literal parts of the pattern, not boundary positions.
# ---------------------------------------------------------------------------
def bounded_hyphen_sub(text, old, new):
    pattern = re.compile(r"(?<![A-Za-z0-9_-])" + re.escape(old) + r"(?![A-Za-z0-9_-])")
    return pattern.subn(new, text)


def bounded_word_sub(text, old, new):
    # Underscore is a legal identifier character, so it stays in the word
    # class here -- this is what keeps "krikos_docsrs" / "krikos_loom" /
    # "krikos_blobs_docsrs" (cfg names not in the map) untouched by the plain
    # "krikos" / "krikos_blobs" lib rules.
    pattern = re.compile(r"(?<![A-Za-z0-9_])" + re.escape(old) + r"(?![A-Za-z0-9_])")
    return pattern.subn(new, text)


def sub_dirs_in_value(value):
    changed_any = False
    for old, new in dir_pairs:
        value, n = bounded_hyphen_sub(value, old, new)
        if n:
            changed_any = True
    return value, changed_any


# ---------------------------------------------------------------------------
# Cargo.toml structural transform.
#
# Deliberately a whitelist, not a blind find/replace over the whole file:
# `repository = "https://github.com/holon-technologies/iroh"` is a real,
# unrenamed GitHub repository (the ADR explicitly leaves the GitHub org/repo
# name out of scope) and sits right next to legitimate renames in the same
# file; a blind substitution would corrupt it (the trailing "krikos" in that
# URL is boundary-legal the same way a real package token is). Only the
# fields below are ever touched.
# ---------------------------------------------------------------------------
HEADER_RE = re.compile(r"^\s*\[+([^\[\]]+)\]+\s*$")
NAME_RE = re.compile(r'^(\s*name\s*=\s*")([^"]*)(".*)$')
KEY_RE = re.compile(r'^(\s*)("?)([A-Za-z0-9_.-]+)\2(\s*=\s*)(.*)$')
# `key.workspace = true` dotted shorthand (Cargo's alternative to
# `key = { workspace = true }`). Checked separately from KEY_RE because
# KEY_RE's char class includes "." for this exact reason and would
# otherwise capture "krikos-resolver.workspace" as one opaque key that never
# equality-matches a bare old_package.
DOTTED_WORKSPACE_KEY_RE = re.compile(r'^(\s*)("?)([A-Za-z0-9_-]+)\2(\.workspace\s*=\s*.*)$')
PATH_FIELD_RE = re.compile(r'(path\s*=\s*")([^"]*)(")')
PACKAGE_FIELD_RE = re.compile(r'(package\s*=\s*")([^"]*)(")')
FEATURE_SLASH_RE = re.compile(r'"([A-Za-z0-9_-]+)(\??)/([A-Za-z0-9_.-]+)"')
FEATURE_DEP_RE = re.compile(r'"dep:([A-Za-z0-9_-]+)(\??)"')
DIR_ARRAY_KEYS = ("members", "exclude")
LIB_ARRAY_KEYS = ("allowed_external_types",)
ARRAY_OPEN_RE = re.compile(
    r"^\s*(members|exclude|allowed_external_types)\s*=\s*\[\s*$"
)
ARRAY_INLINE_RE = re.compile(
    r"^(\s*(?:members|exclude|allowed_external_types)\s*=\s*\[)(.*)(\]\s*)$"
)
QUOTED_RE = re.compile(r'"([^"]*)"')


def sub_lib_in_value(value):
    # `[package.metadata.cargo_check_external_types]`'s allowed_external_types
    # array holds Rust path strings like "krikos_resolver" (bare) or
    # "krikos_resolver::*" (wildcard) -- lib-form (underscore) identifiers,
    # not directory paths, so this uses lib_pairs/exact-or-"::"-prefix
    # matching rather than sub_dirs_in_value's bounded substring search.
    for old, new in lib_pairs:
        if value == old:
            return new, True
        if value.startswith(old + "::"):
            return new + value[len(old):], True
    return value, False


def transform_cargo_toml(text, compat_mode):
    lines = text.split("\n")
    out = []
    changes = 0
    in_lib = False
    in_features = False
    array_key = None  # 'members' or 'exclude' while inside a multi-line array

    for line in lines:
        header_m = HEADER_RE.match(line)
        if header_m:
            header = header_m.group(1).strip()
            in_lib = header == "lib"
            in_features = header == "features"
            array_key = None
            out.append(line)
            continue

        if array_key is not None:
            if line.strip() == "]":
                array_key = None
                out.append(line)
                continue
            if not compat_mode:
                sub_fn = sub_dirs_in_value if array_key in DIR_ARRAY_KEYS else sub_lib_in_value
                def repl(m, sub_fn=sub_fn):
                    v, ch = sub_fn(m.group(1))
                    return f'"{v}"'
                new_line, n = QUOTED_RE.subn(repl, line)
                if n and new_line != line:
                    changes += 1
                    line = new_line
            out.append(line)
            continue

        if not compat_mode:
            inline_m = ARRAY_INLINE_RE.match(line)
            if inline_m:
                key = inline_m.group(1).strip().split("=")[0].strip()
                sub_fn = sub_dirs_in_value if key in DIR_ARRAY_KEYS else sub_lib_in_value
                def repl(m, sub_fn=sub_fn):
                    v, ch = sub_fn(m.group(1))
                    return f'"{v}"'
                body, n = QUOTED_RE.subn(repl, inline_m.group(2))
                # `n` only counts how many quoted strings QUOTED_RE matched,
                # not whether any of them actually changed -- an inline
                # array with any quoted entry (e.g. `members = ["."]`)
                # always has n >= 1, so `if n:` alone reported a false
                # "change" on every such line regardless of content. Compare
                # the assembled replacement line, matching the multi-line
                # array branch above, which already gets this right.
                new_line = inline_m.group(1) + body + inline_m.group(3)
                if n and new_line != line:
                    changes += 1
                line = new_line
                out.append(line)
                continue
            open_m = ARRAY_OPEN_RE.match(line)
            if open_m:
                array_key = open_m.group(1)
                out.append(line)
                continue

        if compat_mode:
            # Narrow, deliberate exception -- see COMPAT_FIX note below.
            # Only touch `path=`/`package=` on lines that carry BOTH: that
            # is exactly the signature of a *-v2/-current entry that
            # points at this repo's own (renamed) package via local path,
            # as opposed to a *-v1 entry pinned to the real upstream crate
            # by `version =` or `git =`, which must NOT change.
            has_path = "path" in line and PATH_FIELD_RE.search(line)
            has_package = "package" in line and PACKAGE_FIELD_RE.search(line)
            if has_path and has_package:
                def repl_path(m):
                    v, ch = sub_dirs_in_value(m.group(2))
                    return m.group(1) + v + m.group(3)
                def repl_pkg(m):
                    v = m.group(2)
                    if v in pkg_map:
                        return m.group(1) + pkg_map[v] + m.group(3)
                    return m.group(0)
                new_line = PATH_FIELD_RE.sub(repl_path, line)
                new_line = PACKAGE_FIELD_RE.sub(repl_pkg, new_line)
                if new_line != line:
                    changes += 1
                    line = new_line
            out.append(line)
            continue

        # --- normal (non-compat, non-array) line handling ---
        name_m = NAME_RE.match(line)
        if name_m:
            value = name_m.group(2)
            table = lib_map if in_lib else pkg_map
            if value in table:
                line = name_m.group(1) + table[value] + name_m.group(3)
                changes += 1
            out.append(line)
            continue

        dotted_m = DOTTED_WORKSPACE_KEY_RE.match(line)
        if dotted_m and dotted_m.group(3) in pkg_map:
            new_key = pkg_map[dotted_m.group(3)]
            line = dotted_m.group(1) + dotted_m.group(2) + new_key + dotted_m.group(2) + dotted_m.group(4)
            changes += 1

        key_m = KEY_RE.match(line)
        if key_m and key_m.group(3) in pkg_map:
            new_key = pkg_map[key_m.group(3)]
            line = key_m.group(1) + key_m.group(2) + new_key + key_m.group(2) + key_m.group(4) + key_m.group(5)
            changes += 1

        def repl_path(m):
            v, ch = sub_dirs_in_value(m.group(2))
            return m.group(1) + v + m.group(3)
        new_line = PATH_FIELD_RE.sub(repl_path, line)
        if new_line != line:
            changes += 1
            line = new_line

        def repl_pkg(m):
            v = m.group(2)
            if v in pkg_map:
                return m.group(1) + pkg_map[v] + m.group(3)
            return m.group(0)
        new_line = PACKAGE_FIELD_RE.sub(repl_pkg, line)
        if new_line != line:
            changes += 1
            line = new_line

        if in_features:
            def repl_slash(m):
                if m.group(1) in pkg_map:
                    return f'"{pkg_map[m.group(1)]}{m.group(2)}/{m.group(3)}"'
                return m.group(0)
            new_line = FEATURE_SLASH_RE.sub(repl_slash, line)
            if new_line != line:
                changes += 1
                line = new_line

            def repl_dep(m):
                if m.group(1) in pkg_map:
                    return f'"dep:{pkg_map[m.group(1)]}{m.group(2)}"'
                return m.group(0)
            new_line = FEATURE_DEP_RE.sub(repl_dep, line)
            if new_line != line:
                changes += 1
                line = new_line

        out.append(line)

    return "\n".join(out), changes


def _rs_lib_patterns(old):
    # An old_lib token is only ever rewritten where it is unambiguously a
    # Rust path/crate identifier -- never inside a plain string literal.
    # This repository hardcodes real, load-bearing string data that
    # contains these same tokens and MUST survive unchanged:
    #   - wire-protocol domain-separation / header strings, e.g.
    #     `"iroh-relay handshake v1 challenge signature"`,
    #     `"x-iroh-relay-client-auth-v1"`, `"iroh-relay-v1"`
    #     (krikos-relay/src/protos/handshake.rs, .../tests/wire_compat.rs) --
    #     renaming these would silently break wire compatibility, which
    #     ADR-0002 explicitly puts out of scope.
    #   - production relay hostnames baked into krikos/src/defaults.rs, e.g.
    #     "use1-1.relay.n0.iroh.link.", and the "iroh.link"/"iroh.computer"
    #     domains referenced elsewhere -- real infrastructure, not an
    #     identifier.
    #   - doc comments linking to upstream/external URLs (github.com/
    #     n0-computer/iroh/..., docs.rs/iroh-tickets, this repo's own
    #     un-renamed github.com/holon-technologies/iroh, ...).
    # A blind bounded-token substitution would corrupt all of the above,
    # because plain string literals and URLs satisfy the same "not
    # [A-Za-z0-9_]" boundary test that a real `krikos_base::Foo` path does.
    # So: whitelist the syntactic positions instead of blacklisting data.
    esc = re.escape(old)
    return [
        # `TOKEN::...` -- the overwhelming majority of real usage.
        re.compile(r"(?<![A-Za-z0-9_])" + esc + r"(?=::)"),
        # `...::TOKEN` -- token as a non-root path segment.
        re.compile(r"(?<=::)" + esc + r"(?![A-Za-z0-9_])"),
        # `use TOKEN` / `use TOKEN;` / `use TOKEN as X;` (no `::` follows).
        re.compile(r"(?<=\buse\s)" + esc + r"(?![A-Za-z0-9_])"),
        # `extern crate TOKEN`.
        re.compile(r"(?<=\bextern crate\s)" + esc + r"(?![A-Za-z0-9_])"),
    ]


def _rs_lib_doc_backtick_pattern(old):
    # `` `TOKEN` `` / `` `TOKEN::Item` `` inside a doc-comment intra-doc
    # link, e.g. [`krikos_base::Foo`] or the bare `` `krikos` ``.
    return re.compile(r"(?<=`)" + re.escape(old) + r"(?=`|::)")


def _rs_lib_doc_bracket_pattern(old):
    # `[TOKEN]` shortcut reference-style doc link, e.g. "used from the
    # [krikos] crate" -- restricted to rustdoc comment lines only (see
    # caller), since outside a doc comment `[krikos]` is not idiomatic Rust
    # and the extra restriction costs nothing.
    return re.compile(r"(?<=\[)" + re.escape(old) + r"(?=\])")


def _rs_pkg_doc_backtick_pattern(old):
    # Hyphens are never legal inside a Rust identifier, so an old_package
    # (hyphenated) token can only legitimately appear in a doc comment
    # mentioning the crate by its published name -- never in `use`/`::`
    # position, so there is no code-syntax equivalent to guard here.
    return re.compile(r"(?<=`)" + re.escape(old) + r"(?=`)")


def _rs_pkg_doc_bracket_pattern(old):
    return re.compile(r"(?<=\[)" + re.escape(old) + r"(?=\])")


def _rs_cfg_feature_pattern(old):
    # Defensive: `#[cfg(feature = "OLD-PACKAGE")]` / `cfg!(feature = ...)`.
    # Zero occurrences exist today (verified), kept for robustness since
    # the plan explicitly calls out #[cfg(...)] attribute references.
    return re.compile(r'(feature\s*=\s*")' + re.escape(old) + r'(")')


DOC_LINE_RE = re.compile(r"^\s*//[!/]")


def _string_literal_mask(line):
    # Best-effort, single-line ranges (start, end) that fall inside a
    # double-quoted string literal, so CODE-syntax patterns (TOKEN::, use
    # TOKEN, extern crate TOKEN) never rewrite the same-looking text when it
    # is DATA rather than a real path. Concretely:
    # `redb::TypeName::new("krikos_blobs::Hash")` in
    # protocols/krikos-blobs/src/hash.rs is a stable on-disk type tag read by
    # the redb embedded database's schema check -- renaming the STRING
    # (as opposed to the real `redb::TypeName` path outside the quotes)
    # would make a database written by a prior build fail to open under a
    # rebuilt binary. `event!(target: "krikos::_events::...")` tracing
    # target strings are the same shape; both are conservatively left
    # alone here rather than trying to classify which string literals are
    # "just" a local convention vs. a persisted/external contract.
    ranges = []
    in_str = False
    start = None
    i = 0
    n = len(line)
    while i < n:
        c = line[i]
        if in_str and c == "\\":
            i += 2
            continue
        if c == '"':
            if in_str:
                ranges.append((start, i))
                in_str = False
            else:
                in_str = True
                start = i + 1
        i += 1
    if in_str:
        ranges.append((start, n))
    return ranges


def _in_ranges(pos, ranges):
    return any(a <= pos < b for a, b in ranges)


def _apply_masked(line, patterns, new):
    # More than one whitelist pattern can match the exact same span --
    # `use krikos_base::Foo` satisfies both "TOKEN followed by ::" and "TOKEN
    # preceded by 'use '" at identical (start, end) offsets. Without
    # deduplication the same span gets spliced twice, and the second splice
    # uses offsets computed against the pre-edit line, corrupting the
    # result (observed: "krikos_base" -> "krikos_basese"). Keep exactly one
    # match per unique (start, end) span.
    mask = _string_literal_mask(line)
    seen_spans = set()
    matches = []
    for pat in patterns:
        for m in pat.finditer(line):
            span = (m.start(), m.end())
            if span in seen_spans:
                continue
            seen_spans.add(span)
            matches.append(m)
    matches = [m for m in matches if not _in_ranges(m.start(), mask)]
    matches.sort(key=lambda m: m.start(), reverse=True)
    for m in matches:
        line = line[: m.start()] + new + line[m.end() :]
    return line, len(matches)


def transform_rs(text):
    changes = 0
    lines = text.split("\n")
    for i, line in enumerate(lines):
        is_doc_line = bool(DOC_LINE_RE.match(line))
        for old, new in pkg_pairs:
            if is_doc_line:
                line, n = _rs_pkg_doc_backtick_pattern(old).subn(new, line)
                changes += n
                line, n = _rs_pkg_doc_bracket_pattern(old).subn(new, line)
                changes += n
            def repl_cfg(m, new=new):
                return m.group(1) + new + m.group(2)
            new_line = _rs_cfg_feature_pattern(old).sub(repl_cfg, line)
            if new_line != line:
                changes += 1
                line = new_line
        for old, new in lib_pairs:
            line, n = _apply_masked(line, _rs_lib_patterns(old), new)
            changes += n
            if is_doc_line:
                line, n = _rs_lib_doc_backtick_pattern(old).subn(new, line)
                changes += n
                line, n = _rs_lib_doc_bracket_pattern(old).subn(new, line)
                changes += n
        lines[i] = line
    return "\n".join(lines), changes


# ---------------------------------------------------------------------------
# File enumeration and dispatch.
# ---------------------------------------------------------------------------
out = subprocess.run(["git", "ls-files", "-z"], cwd=root, check=True, capture_output=True).stdout
all_files = [p for p in out.decode("utf-8").split("\0") if p]

COMPAT_CARGO_FILES = {
    "compat/iroh-blobs-v0-103-interop/Cargo.toml",
    "compat/iroh-gossip-v0-101-interop/Cargo.toml",
    "compat/relay-v1-interop/Cargo.toml",
}

summary = {"toml": 0, "rs": 0, "compat_fix": 0, "skipped_exempt": 0, "skipped_vendor": 0, "skipped_other": 0}
touched_exempt = []

diff_lines = []

for rel in sorted(all_files):
    # COMPAT_FIX: see the narrow exception documented at the top of this
    # script and in transform_cargo_toml's compat_mode branch. This is the
    # ONLY place an exempted path is intentionally written.
    if rel in COMPAT_CARGO_FILES:
        fpath = root / rel
        text = fpath.read_text()
        new_text, changes = transform_cargo_toml(text, compat_mode=True)
        if changes:
            summary["compat_fix"] += changes
            diff_lines.append(f"COMPAT-FIX: {rel} ({changes} field(s): path=/package= on *-v2/-current entries only)")
            if not dry_run:
                fpath.write_text(new_text)
        continue

    if is_exempt(rel):
        summary["skipped_exempt"] += 1
        continue

    if rel == "scripts/apply-rebrand.sh":
        # Never rewrite this script's own source.
        summary["skipped_other"] += 1
        continue

    if rel.startswith("vendor/"):
        # Task 2 already owns vendor/*/Cargo.toml identity (via the checked
        # -in patches). Task 3 does not touch the vendored tree at all, so
        # it cannot desync a working-tree file from its patch.
        summary["skipped_vendor"] += 1
        continue

    basename = rel.rsplit("/", 1)[-1]
    fpath = root / rel

    if basename == "Cargo.toml":
        text = fpath.read_text()
        new_text, changes = transform_cargo_toml(text, compat_mode=False)
        if changes:
            summary["toml"] += 1
            diff_lines.append(f"TOML: {rel} ({changes} field(s))")
            if not dry_run:
                fpath.write_text(new_text)
        continue

    if rel.endswith(".rs"):
        text = fpath.read_text()
        new_text, changes = transform_rs(text)
        if changes:
            summary["rs"] += 1
            diff_lines.append(f"RS:   {rel} ({changes} token(s))")
            if not dry_run:
                fpath.write_text(new_text)
        continue

    summary["skipped_other"] += 1

print()
print("=== Content rewrite plan/result ===" if not dry_run else "=== DRY RUN: content rewrite plan ===")
for line in diff_lines:
    print(line)
print()
print(f"Cargo.toml files changed: {summary['toml']}")
print(f"*.rs files changed:       {summary['rs']}")
print(f"compat/*.toml field fixes (path=/package= only): {summary['compat_fix']}")
print(f"files skipped (exempted per rename-map.toml): {summary['skipped_exempt']}")
print(f"files skipped (vendor/, Task 2's domain):      {summary['skipped_vendor']}")
print(f"files skipped (out of Task 3 scope: not Cargo.toml/.rs): {summary['skipped_other']}")

exempt_touched = [l for l in diff_lines if any(
    glob_match(l.split(": ", 1)[1].split(" (")[0], e["path"]) for e in exemptions if "path" in e
) and not l.startswith("COMPAT-FIX")]
if exempt_touched:
    print("\nFATAL: the following exempted paths were about to be rewritten:")
    for l in exempt_touched:
        print(f"  {l}")
    sys.exit(1)

if dry_run:
    print("\nDry run only -- nothing written. Re-run with --apply to write.")
PYEOF
